
######## ember-osf settings ########
# local:
#   CLIENT_ID: null
#   PERSONAL_ACCESS_TOKEN: null
#   OAUTH_SCOPES: osf.full_read osf.full_write

stage:
   CLIENT_ID: a025504ed97248c8bd9394700e9f9c05
   PERSONAL_ACCESS_TOKEN: CvnTVVwjYZDNBbKStB1eX9wbeUgmV9xVUUmOS9uM8RYdQaIzeSjR4tK9ZcvoluVo75WNH4
   OAUTH_SCOPES: osf.full_read osf.full_write

# stage2:
#   CLIENT_ID: null
#   PERSONAL_ACCESS_TOKEN: null
#   OAUTH_SCOPES: osf.full_read osf.full_write

# test:
#   CLIENT_ID: null
#   PERSONAL_ACCESS_TOKEN: null
#   OAUTH_SCOPES: osf.full_read osf.full_write
######### end ember-osf ##########
